server:
  port: 9001
spring:
  redis:
    database: 0
    host: localhost
    password: 123456
    port: 6379
    lettuce:
      pool:
        max-wait: 1ms
        max-active: 8
        max-idle: 10
        min-idle: 5
      shutdown-timeout: 100ms
